<?php

/**
 * @file
 * Primary module hooks for simple_gitlab_manager module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function simple_gitlab_manager_theme() {
  return [
    'simple_gitlab_manager' => [
      'render element' => 'form',
    ]
  ];
}



/**
 * @param $variables
 * Implements hook_page_attachments()
 */
function simple_gitlab_manager_page_attachments(&$variables) {
//  $current_path = \Drupal::service('path.current')->getPath();
//  if($current_path == '/simple-gitlab-manager'){
    $variables['#attached']['library'][] =  'simple_gitlab_manager/simple_gitlab_manager';
//  }
}
